controlsfx/controlsfx

- build.gradle
- controlsfx/src/main/java/impl/org/controlsfx/skin/AutoCompletePopup.java
- controlsfx/src/main/java/org/controlsfx/control/BreadCrumbBar.java
- controlsfx/src/main/java/org/controlsfx/control/HyperlinkLabel.java
This PR removes unnecessary use of `EventHandlerManager` from controls which already have exposed `setEventHandler`/ `addEventHandler` methods in them.
> Remove EventHandlerManager from scene graph elements

- controlsfx/src/main/java/module-info.java
I faced an issue in my project where I am not using javafx.web. I got the following error on application startup:
> java.lang.module.FindException: Module javafx.web not found, required by org.controlsfx.controls
Making this module as optional module solves the problem.
> Make javafx.web and javafx.media as optional modules

- controlsfx/src/main/java/org/controlsfx/control/Notifications.java
Utils.getWindow(null) can return null and therefore we need to check if
there is a Window or we use primary window.
> #1140 Fix NPE in Notifications

- controlsfx/src/main/java/org/controlsfx/control/Notifications.java
The position of the elements does not use the notification position
anymore. It uses the position where the notifications will be shown.
The following errors are fixed with this change:
- Fix old notifications shown not aligned with new notifications
when the window is moved or owner is set.
- Fix animation, it does not use the position of the notification
because if the animation is not finished, the position is not
correct. Previously, the position between the first and second
notification was not right if there were several notifications.
This is the fix for the problem in Notifications position.
Issue: #1114(#1114)
New features/fixes easily reproducible with HelloNotifications class:
New notifications are aligned with the old ones.
All notifications are correctly aligned.
the …
> #1114 Notifications: Fix notifications position

- controlsfx/src/main/java/org/controlsfx/dialog/ExceptionDialog.java
If you set a preferred width for the exception dialog, then the content message is simply cut-off if it is too long. 
With this fix, the content should wrap nicely.
> Wrap content in exception dialog

- controlsfx/src/main/java/org/controlsfx/control/TaskProgressView.java
As discussed in #1118, a simple way to have TaskProgressView retaining a task after it's succeeded, cancelled or failed
> TaskProgressView - new flag to retain tasks when succeeded, cancelled or failed

- build.gradle
Fix #1172
The left shift operator (`<<`) is deprecated since Gradle 3.2 and was removed from Gradle 5. With the left shift operator, controlsfx will not build using Gradle 5. I replaced it with the `doLast` block, which makes it build again with Gradle 5.
> Fix build with Gradle 5

- controlsfx/src/main/java/org/controlsfx/control/textfield/AutoCompletionBinding.java
This PR fixes #875.
My motivation: When using the autocompletion feature in a table cell editor, likelihood increases to run into the problem described in #875, because the table cell editor is removed from the scene graph frequently.
To avoid `IllegalStateException`s ("Can not show popup. The node must be attached to a scene/window.") thrown in `AutoCompletePopup.show(Node)`, we do the check in advance.
Thanks for having a look at it!
> Validate completionTarget before showing autocomplete popup

- controlsfx/src/main/java/org/controlsfx/validation/ValidationResult.java
This is needed for Issue #1163. Currently the ValidationSupport model does not recognize messages that have the INFO Severity. This merge will add in that support.
Also refactor how messages are stored. Use one ArrayList instead of creating an Arraylist for each Severity type.
> added support for the INFO Severity and refactored the messages storage

- controlsfx-samples/src/main/java/org/controlsfx/samples/HelloValidation.java
- controlsfx-samples/src/main/resources/org/controlsfx/samples/validation.css
- Added info severity to the HelloValidation sample in the ComboBox.
- Clean up code format and also removed excess comments
- Changed color of fx-effect to skyblue.
-  I was getting a css error from the previous rbga value using **java8u211** on **Windows 10** 
- [This JavaFX Bug has been confirmed to not be addressed in Java 8](https://bugs.openjdk.java.net/browse/JDK-8182152)
I didn't do anything for OK Severity. Not sure what the goal for this severity is for. I can add it in once I understand the intent of this. (Maybe use it to check when a user enter in a valid value?)
> PR for Issue #1163

- controlsfx-samples/src/main/java/org/controlsfx/samples/tableview/HelloTableFilter.java
- controlsfx/src/main/java/org/controlsfx/control/table/FilterPanel.java
- controlsfx/src/main/java/org/controlsfx/control/table/TableFilter.java
This "forward" ports https://github.com/controlsfx/controlsfx/pull/1142 and thus fixes https://github.com/controlsfx/controlsfx/issues/1188.
> Fix filter.png not found

- controlsfx/src/main/java/org/controlsfx/control/CheckListView.java
As requested, a PR with a fix for #1219
> Fix NPE in CheckListView 

- controlsfx/src/main/java/org/controlsfx/control/CheckComboBox.java
- controlsfx/src/main/java/org/controlsfx/control/tableview2/TableView2.java
Make CheckComboBox default property available to FXML.
Fixes #1227
> #1227: Add 'DefaultProperty' annotation to CheckComboBox

- controlsfx/build.gradle
- settings.gradle
Fixes #1237
In Gradle 5.0, the OSGi Plugin was deprecated. We need to modify the build scripts.
The details: [https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle](https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle)
> Add Export-Package for OSGi in MF

- controlsfx/src/main/java/impl/org/controlsfx/skin/AutoCompletePopup.java
When AutoCompletePopup is displayed for TextField in right to left layout, it's in incorrect location. I applied corrections to x position based on [Tooltip's code](https://github.com/openjdk/jfx/blob/master/modules/javafx.controls/src/main/java/javafx/scene/control/Tooltip.java#L893) in javafx repository.
Fixes #1247
> Fix AutoCompletePopup location in RTL layouts

- controlsfx/src/main/java/impl/org/controlsfx/skin/RatingSkin.java
As of now it not possible to easily customize the look of the rating control apart from changing the look via css. Other customization like using font-based glyphs for the star are not possible.
This PR makes the creation of the star node protected so that one customize it by overriding.
> Allow user to overwrite the rating icon

- controlsfx/build.gradle
- controlsfx/src/main/java/module-info.java
With PR #1253, javafx.swing is no longer required and is now redundant.
Fixes #1252
> Remove redundant javafx.swing module

- build.gradle
- controlsfx/src/main/java/impl/org/controlsfx/ReflectionUtils.java
- controlsfx/src/main/java/org/controlsfx/glyphfont/Glyph.java
- controlsfx/src/main/java/org/controlsfx/glyphfont/GlyphFont.java
This fixes #1245.
Currently, `org.controlsfx.glyphfont.GlyphFont` uses reflection to add a user-agent style sheet ("glyphfont.css") which only affects `org.controlsfx.glyphfont.Glyph`. This reflection does not work when JavaFX is on the module path without an `--add-exports` argument.
This PR removes the use of reflection in `GlyphFont` and overrides [`Region#getUserAgentStylesheet()`][1] in `Glyph` to accomplish the same thing. That method is designed exactly for this use case:
>An implementation may specify its own user-agent styles for this Region, and its children, by overriding this method. These styles are used in addition to whatever user-agent stylesheets are in use. This provides a mechanism for third parties to introduce styles for custom controls. 
[1]: …
> Fix InaccessibleObjectException in GlyphFont

- controlsfx/src/main/java/impl/org/controlsfx/skin/AutoCompletePopup.java
This fixes Right to Left layout. The fix is consistent between 9.0.0 and master branch.
Fixes #1247
> Fix RTL in AutoComplete

- controlsfx/build.gradle
- controlsfx/src/test/java/org/controlsfx/control/SearchableComboBoxTest.java
We recently enabled tests on 9.0.0 branch. This PR takes us a step forward and enables headless testing using `openjfx-monocle` from TestFX.
> Enable headless testing

- controlsfx/src/main/java/impl/org/controlsfx/skin/BreadCrumbBarSkin.java
- controlsfx/src/main/java/org/controlsfx/control/BreadCrumbBar.java
Moves the static BreadCrumbButton inner class from the inaccessible
impl.org.controlsfx.skin.BreadCrumbBarSkin class to the publicly
accessible org.controlsfx.controls.BreadCrumbBar class.
This allows users to customize the appearance of the BreadCrumbBar via
its setCrumbFactory method. While it is possible to call this method
with a generic Button, the internal layouting of the skin relies on
BreadCrumbButton to layout the buttons in an overlapping way.
This (to my best understanding) implements the solution outlined by @abhinayagarwal in
controlsfx/controlsfx#1109
> Move BreadCrumbButton to public api

- controlsfx/src/main/java/impl/org/controlsfx/skin/ToggleSwitchSkin.java
When a ToggleSwitch is shown already selected, then the user unselects
it, the thumb animation does not fire properly. This commit fixes that.
Tested the case where layoutChildren() is called when transition is
active(#812), by changing the font size, works fine.
> Fix ToggleSwitch animation when selected

- .github/workflows/cla.yml
Uses Github Action to automatically verify if a contributor has signed [ControlsFX CLA](https://cla.controlsfx.org).  The workflow does the following:
1. If a contributor is found, it will add a label `CLA-VERIFIED` to the PR
2. If a contributor is not found, it will add a label `CLA` to the PR and comment on the PR
Fixes #1255
> Add workflow for CLA verification

- controlsfx/src/main/java/impl/org/controlsfx/skin/CheckComboBoxSkin.java
If an item gets selected in an CheckComboBox, a subsequent hit on TAB
throws a NullPointerException. This commit fixes this bug.
fixes #1297
> Issue #1297: Fix NPE when hitting TAB in CheckComboBox

- controlsfx/src/main/java/org/controlsfx/control/action/Action.java
Hi,
Using org.controlsfx.control.action.Action.setSelected(boolean) changes the selected state of ActionCheck actions correctly but does not trigger the corresponding EventHandler. 
So, changing the state programmatically, using this method, does not make the application do what it would when clicking  toogleButton or checkMenu elements created with the ActionCheck (activate or deactivate the rendering of an animation for instance)
> Action.setSelected(boolean) now triggers the EventHandler if needed,

- controlsfx/src/main/java/impl/org/controlsfx/skin/NotificationBar.java
- controlsfx/src/main/java/org/controlsfx/control/Notifications.java
Simplified various places in the code.
I think the minHeight is not required, the content should provide the minimum height.
The computeMinHeight/Width methods caused issues. They also were illogical, because graphic is only a small part of it's content.
After this change it seems to work again.
Without this change, and when the graphic is set (for example with .graphic(new Label(text)) )
Then it looked like the following:
I've also removed the VPos logic, because it now always positions it in the center, and it also doesn't really make sense to me.
> Fix notifications

- controlsfx/build.gradle
- controlsfx/src/main/java/impl/org/controlsfx/tableview2/TableRow2Skin.java
- controlsfx/src/test/java/org/controlsfx/control/tableview2/TableView2Test.java
Fixes #1361 
The non-responsiveness came from continuous listener adding while creating the cell that is not visible and be garbage collected immediately. Moving the getCell(..) call further down to be performed after the visibility check is avoiding unnessesary creation of elements.
> TableView2: Check cell visibility before add/remove listener

- controlsfx/src/main/java/impl/org/controlsfx/spreadsheet/SpreadsheetGridView.java
- controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetView.java
Applies changes discussed in https://github.com/controlsfx/controlsfx/issues/957
fix #957
> Allow SpreadsheetView CSS to be overridden

- controlsfx/src/main/java/org/controlsfx/dialog/CommandLinksDialog.java
- controlsfx/src/main/java/org/controlsfx/dialog/ExceptionDialog.java
- controlsfx/src/main/java/org/controlsfx/dialog/FontSelectorDialog.java
- controlsfx/src/main/java/org/controlsfx/dialog/LoginDialog.java
- controlsfx/src/main/java/org/controlsfx/dialog/ProgressDialog.java
Fixes #1162
Added documentation with usage examples for: CommandLinksDialog, CommandLinksButtonType
and descriptions for: ExceptionDialog, FontSelectorDialog, LoginDialog, ProgressDialog.
> Add missing JavaDoc for Dialog classes

- controlsfx/src/main/java/org/controlsfx/property/editor/Editors.java
Constructors of wrapper classes for primitive types are deprecated  for removal in Java 16 (see [JEP 390](https://openjdk.java.net/jeps/390)). They should be removed when [JEP 402](https://openjdk.java.net/jeps/402) is done.
Right now `Editors.createNumericEditor` is still using reflection to call their constructors to create objects, which makes it impossible to work with Valhalla, and we should avoid that.
> Create primitive type wrapper objects without a constructor

- controlsfx/src/main/java/impl/org/controlsfx/skin/ToggleSwitchSkin.java
- controlsfx/src/main/resources/org/controlsfx/control/toggleswitch.css
> ToggleSwitch: Add focused style and toggle using SPACE key

- controlsfx/src/main/java/org/controlsfx/control/PopOver.java
As Described under https://github.com/controlsfx/controlsfx/issues/1441
The Error on Window closing while a PopOver is open is caused by the fadeout time.
Can be fixed by adding a OnCloseRequest-listener to the OwnerWindow which then closes the PopOver without delay.
> Remove event filter when owner window is hiding 

- controlsfx/src/main/java/impl/org/controlsfx/skin/RangeSliderSkin.java
Fixes #1506 
It is a very weird issue that shouldn't happen. But in that case, this PR simply adds a null check and sets `preDragThumbPoint` to the coordinates first drag event.
> Prevent possible NPE while dragging the thumbs of the RangeSlider control

- controlsfx-samples/src/main/java/org/controlsfx/samples/HelloHyperlinkLabel.java
- controlsfx-samples/src/main/java/org/controlsfx/samples/dialogs/HelloDialogs.java
Fixing two resource bugs within the sample application. 
1. HelloHyperlinkLabel was looking for a style.css file that does not exist anywhere (and is probably not necessary). 
2. HelloDialogs was attempting to refer to a parent directory; but this doesn't work as the developer expected in the context of a running JAR. E.g., getResource("."), getResource(".."), getResource("../.."), etc., all resolve to null. This is not the case when running in a non-JAR context.
Easy to reproduce these using "gradle run" and trying to load the hyperlink demo, or the dialog pop with custom image demo; neither work currently.
Fixes #1527
> Fixing two resource bugs within the sample application. 

- controlsfx/src/main/java/org/controlsfx/property/editor/AbstractPropertyEditor.java
> PropertyEditors now subscribe to the item's ObservableValue even if the editor is read-only

- controlsfx/src/main/java/org/controlsfx/tools/Borders.java
Fixes #1538 
This PR modifies the `Borders#StrokeBorder` class to avoid doing node creation on layout passes, by moving out the border creation to a method that is called only after the title label creation and when the width of the stackPane that wraps the user node changes.
The title label layout is overwritten only to relocate it properly.
This changes should increase notably the performance of any node wrapped with `Borders`.
Running the test attached to the issue shows now:
```
needs layout = false
needs layout = true
needs layout = false
needs layout = true
```
(that's it, no more infinite layout passes)
> Move border creation outside of layout pass

- controlsfx/src/main/java/org/controlsfx/dialog/Wizard.java
I believe this provides the access necessary to resolve #756, #976, #999 and #1388.
I have chosen to make `getDialog()` public rather than alternative methods such as a `setDialog()` or making `dialog` itself protected as I believe this offers the simplest possible change to meet the needs of these issues (and my own).
I can't see any obvious disadvantage to making the Wizard dialog accessible in this way, but if there is some subtlety that I have missed, please let me know.
> Provide a public getter method for the Dialog used by a Wizard
