controlsfx/controlsfx

- controlsfx/src/main/java/org/controlsfx/control/Notifications.java
It provides multimonitor support:
#1121
> #1121 Notifications: Multimonitor support

- controlsfx/src/main/java/org/controlsfx/control/decoration/Decorator.java
This is the new PR against the master branch instead of the 9.0.0 branch.
Old PR: https://github.com/controlsfx/controlsfx/pull/1108
> Fix style of ContextMenu after applying decoration (master branch)

- controlsfx/src/main/resources/org/controlsfx/control/toggleswitch.css
see https://github.com/controlsfx/controlsfx/issues/1144
> Bug Fix for ToggleSwitch's TextFill

- controlsfx/src/main/java/impl/org/controlsfx/skin/ListActionViewSkin.java
- controlsfx/src/main/java/impl/org/controlsfx/skin/ListSelectionViewSkin.java
Source and Target list not getting updated is fixed with this PR
Fixes #1097
> #1097 Items should have bidirectional binding

- controlsfx/src/main/resources/org/controlsfx/control/notificationpopup.css
> #1122 Notifications: Fix shifting of the notifications(Master)

- readme.md
The PR adds badges for:
* branch build status from Travis CI: `master` and `9.0.0` 
* latest release versions from Maven Central: `8.x.x` and `11.x.x (or later)`
> Add badges for release and build status of both branches

- controlsfx/src/main/java/impl/org/controlsfx/skin/CustomTextFieldSkin.java
- controlsfx/src/test/java/org/controlsfx/control/textfield/CustomTextFieldTest.java
> Fix for Issue #1178

- controlsfx/src/main/java/org/controlsfx/dialog/ExceptionDialog.java
Extra: simplify code and use localised exception message
Fixes #1211
> Wrap long exception message

- controlsfx-samples/src/main/java/org/controlsfx/samples/textfields/HelloAutoComplete.java
- controlsfx/src/main/java/impl/org/controlsfx/skin/AutoCompletePopupSkin.java
- controlsfx/src/main/java/org/controlsfx/control/textfield/AutoCompletionBinding.java
- Set custom skins for the popup
- Customization options for the default skin
> Auto completion improvements

- controlsfx/src/main/java/org/controlsfx/validation/ValidateEvent.java
- controlsfx/src/main/java/org/controlsfx/validation/ValidationSupport.java
Adds a method to manually force validation for control(s). Fixes #1283
> #1283 Add revalidate method

- controlsfx/src/main/java/org/controlsfx/validation/ValidationSupport.java
Fix #1284 for master (java 8).
> Ensure thread safety in ValidationSupport.controls

- controlsfx-samples/src/main/java/org/controlsfx/samples/tableview/HelloTableFilter.java
There looks to be some raw uses of classes in controlsfx without the proper type parameter. If desired, I will generify the rest of the project as well.
> Fix raw use of TableView, and parameter ordering

- build.gradle
- controlsfx/src/main/java/impl/org/controlsfx/ReflectionUtils.java
- controlsfx/src/main/java/impl/org/controlsfx/skin/GridViewSkin.java
> Fix VirtualFlow access in GridViewSkin

- controlsfx/src/main/java/org/controlsfx/tools/Utils.java
Copied solution from branch master.
Fixes #1213
> NPE from Notifications.show() if app has no window open

- controlsfx/src/main/java/impl/org/controlsfx/skin/CheckComboBoxSkin.java
#1222 fixed the issue in CheckListView but we missed CheckComboBox.
Fixes #1226
> #1226: Fix NPE in CheckComboBox

- controlsfx/src/main/java/impl/org/controlsfx/ImplUtils.java
> PR for Issue #1324

- controlsfx-samples/src/main/java/org/controlsfx/samples/HelloToggleSwitch.java
- controlsfx-samples/src/main/resources/org/controlsfx/samples/toggleSwitchSample.css
- controlsfx/src/main/java/impl/org/controlsfx/skin/ToggleSwitchSkin.java
> Fix y coordinate computation when thumb is bigger than thumb-area

- controlsfx/src/main/java/org/controlsfx/control/textfield/TextFields.java
> FadeTransition should be based on clear button visibility property and TextField text property

- controlsfx/src/main/java/org/controlsfx/control/SearchableComboBox.java
> Add default style-class in SearchableComboBox

- controlsfx/src/main/java/org/controlsfx/property/editor/Editors.java
- controlsfx/src/main/java/org/controlsfx/property/editor/NumericField.java
- controlsfx/src/test/java/org/controlsfx/property/editor/NumericPropertyZeroTest.java
Hello, after hitting this issue in Property Sheets I thought I could take the time to create the fix based on the suggestion in issue #1275 and create the unit test for it too.
> Fix and unit test for issue #1275

- controlsfx/src/main/java/impl/org/controlsfx/skin/SearchableComboBoxSkin.java
> Fix prompt text not showing in SearchableComboBox

- controlsfx/src/main/java/org/controlsfx/control/Notifications.java
> #1384: Fix using active popups as owners for new popups

- controlsfx/src/main/java/org/controlsfx/control/spreadsheet/SpreadsheetView.java
Comment of function rowHeaderWidthProperty of SpreadsheetView
> Orthographic correction of comment

- .github/workflows/build.yml
- .github/workflows/release.yml
> Package jars with resource bundles

- controlsfx/src/main/java/org/controlsfx/control/Notifications.java
> Fix Notifications animation bug in multiscreen environment

- controlsfx/src/main/java/org/controlsfx/control/Notifications.java
> Expose public api that allows customization of Notifications' style class

- controlsfx/src/main/java/impl/org/controlsfx/skin/ExpandableTableRowSkin.java
> Fixed NPE while filtering on table column

- controlsfx/src/main/java/org/controlsfx/control/table/ColumnFilter.java
> Fixed NPE while removing items from ObservableList

- controlsfx/src/main/java/impl/org/controlsfx/skin/CheckComboBoxSkin.java
- controlsfx/src/main/java/org/controlsfx/control/CheckComboBox.java
> Add COMBO_BOX_ROWS_TO_MEASURE_WIDTH_KEY field to CheckComboBox

- controlsfx/src/main/java/impl/org/controlsfx/skin/GridRowSkin.java
- controlsfx/src/main/java/impl/org/controlsfx/skin/GridViewSkin.java
> GridView: Adapt to VirtualFlow changes in JavaFX 17

- controlsfx-samples/src/main/java/org/controlsfx/samples/HelloHyperlinkLabel.java
- controlsfx/src/main/java/impl/org/controlsfx/skin/HyperlinkLabelSkin.java
- controlsfx/src/main/java/org/controlsfx/control/HyperlinkLabel.java
> HyperlinkLabel focus property update

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.gradle
- controlsfx-samples/build.gradle
- controlsfx-samples/src/main/java/module-info.java
- controlsfx-samples/src/main/java/org/controlsfx/ControlsFXSampler.java
- controlsfx-samples/src/main/java/org/controlsfx/ControlsFXSamplerProject.java
- controlsfx-samples/src/main/resources/META-INF/services/fxsampler.FXSamplerProject
- controlsfx/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Adds support for Gradle 7+ and JDK 17+
Fixes #1370
> Use Gradle 7+

- controlsfx/src/main/java/impl/org/controlsfx/skin/SearchableComboBoxSkin.java
> Avoid recursive call to layout children

- controlsfx/build.gradle
- settings.gradle
> Fix Gradle build failure

- .github/workflows/release.yml
- build.gradle
- mavenPublish.gradle
- settings.gradle
> Use Gradle Nexus Publish Plugin

- controlsfx/src/main/java/org/controlsfx/control/CheckBitSetModelBase.java
- controlsfx/src/main/java/org/controlsfx/control/CheckComboBox.java
- controlsfx/src/test/java/org/controlsfx/control/CheckBitSetModelBaseTest.java
> CheckComboBox ListChangeListener should fire once on change

- controlsfx/src/main/java/impl/org/controlsfx/skin/RangeSliderSkin.java
Fixes jumping of range bar when dragging range bar in vertical range slider.
Fixes #1099
> Update RangeSliderSkin as fix for #1521

- controlsfx/src/main/java/impl/build/transifex/Transifex.java
- controlsfx/src/main/java/module-info.java
> Use Transifex API v3
